on: [push, workflow_dispatch]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HubSpot Project Upload Action
        uses: HubSpot/hubspot-project-actions/project-upload@v0.0.1
        with:
          account_id: ${{ secrets.hubspot_account_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
