on: [push, workflow_dispatch]
env:
  DEFAULT_PERSONAL_ACCESS_KEY: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
  DEFAULT_ACCOUNT_ID: ${{ secrets.HUBSPOT_ACCOUNT_ID }}
  DEFAULT_PROFILE: "prod"
  DEFAULT_CLI_VERSION: "7.6.0-beta.3"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot Project Upload Action
        uses: HubSpot/hubspot-project-actions/project-upload@main
        with:
          project_dir: ./my-oauth-app
